# Generated by Django 6.0.3 on 2026-04-17 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('students', '0002_student_student_status_yr_cls_sec_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_active', 'publish_date', 'expiry_date'], name='notice_active_pub_exp_idx'),
        ),
    ]
