# Generated by Django 5.2.12 on 2026-04-08 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('examinations', '0002_alter_examschedule_unique_together_and_more'),
        ('students', '0004_remove_student_parent_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(help_text='Uploaded textbook page image', upload_to='questions/ai_uploads/')),
                ('num_mcq', models.IntegerField(default=10, help_text='Number of MCQs to generate')),
                ('num_creative', models.IntegerField(default=5, help_text='Number of creative questions to generate')),
                ('num_short_answer', models.IntegerField(default=5, help_text='Number of short answer questions to generate')),
                ('additional_prompt', models.TextField(blank=True, help_text='Additional instructions for AI (topics, focus areas, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('prompt_used', models.TextField(blank=True, help_text='The full prompt sent to AI')),
                ('ai_response_raw', models.JSONField(blank=True, help_text='Raw JSON response from AI', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed')),
                ('language', models.CharField(default='bilingual', help_text='Generation language: english, bengali, bilingual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_requests', to='students.classlevel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_requests', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_requests', to='academics.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_requests', to='examinations.term')),
            ],
            options={
                'verbose_name': 'AI generation request',
                'verbose_name_plural': 'AI generation requests',
                'db_table': 'questions_ai_generation_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, help_text='Specific topic/chapter name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='students.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='students.classlevel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_banks', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='academics.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='examinations.term')),
            ],
            options={
                'verbose_name': 'question bank',
                'verbose_name_plural': 'question banks',
                'db_table': 'questions_question_bank',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'class_level', 'subject', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question in English')),
                ('question_text_bn', models.TextField(blank=True, help_text='Question in Bengali')),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ (Multiple Choice Question)'), ('creative', 'Creative Question (CQ)'), ('short_answer', 'Short Answer')], default='mcq', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('bloom_level', models.CharField(choices=[('knowledge', 'Knowledge'), ('comprehension', 'Comprehension'), ('application', 'Application'), ('analysis', 'Analysis'), ('synthesis', 'Synthesis'), ('evaluation', 'Evaluation')], default='knowledge', help_text="Bloom's taxonomy level (for creative questions)", max_length=20)),
                ('marks', models.IntegerField(default=1, help_text='Marks allocated for this question')),
                ('answer_explanation', models.TextField(blank=True, help_text='Correct answer explanation')),
                ('answer_explanation_bn', models.TextField(blank=True, help_text='Correct answer explanation in Bengali')),
                ('ai_generated', models.BooleanField(default=False, help_text='Whether this question was AI-generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Whether question has been reviewed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('generation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_questions', to='questions.aigenerationrequest')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questionbank')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'questions_question',
                'ordering': ['question_bank', 'question_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(help_text='Option text', max_length=500)),
                ('option_text_bn', models.CharField(blank=True, help_text='Option text in Bengali', max_length=500)),
                ('label', models.CharField(help_text='Option label (A, B, C, D)', max_length=1)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this is the correct answer')),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'mcq'}, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'verbose_name': 'question option',
                'verbose_name_plural': 'question options',
                'db_table': 'questions_question_option',
                'ordering': ['question', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'difficulty'], name='questions_q_questio_086a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_bank', 'is_approved'], name='questions_q_questio_8c8d82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionoption',
            unique_together={('question', 'label')},
        ),
    ]
