# Generated by Django 5.2.12 on 2026-04-09 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('students', '0004_remove_student_parent_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('paper_type', models.CharField(choices=[('test', 'Test'), ('quiz', 'Quiz'), ('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('practice', 'Practice Paper'), ('mock', 'Mock Exam')], default='test', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='medium', max_length=10)),
                ('total_marks', models.IntegerField(default=100, help_text='Total marks for this paper')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('instructions', models.TextField(blank=True, help_text='General instructions for students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this paper is ready for use')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='students.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_papers', to=settings.AUTH_USER_MODEL)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='questions.questionbank')),
            ],
            options={
                'verbose_name': 'question paper',
                'verbose_name_plural': 'question papers',
                'db_table': 'questions_question_paper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order in the paper')),
                ('marks', models.IntegerField(default=1, help_text='Marks for this question in this paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_appearances', to='questions.question')),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='questions.questionpaper')),
            ],
            options={
                'verbose_name': 'question paper question',
                'verbose_name_plural': 'question paper questions',
                'db_table': 'questions_question_paper_question',
                'ordering': ['question_paper', 'order'],
                'unique_together': {('question_paper', 'question')},
            },
        ),
    ]
