# Generated by Django 5.2.12 on 2026-04-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('examinations', '0003_examschedule_is_published_and_more'),
        ('questions', '0002_questionpaper_questionpaperquestion'),
        ('students', '0004_remove_student_parent_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationrequest',
            name='question_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_requests', to='questions.questionpaper'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_questions', to='questions.questionpaper'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='students.classlevel'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_papers', to='examinations.term'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.questionbank'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_papers', to='questions.questionbank'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='total_marks',
            field=models.IntegerField(default=0, help_text='Total marks for this paper'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_paper', 'is_approved'], name='questions_q_questio_60f76e_idx'),
        ),
    ]
