# Generated by Django 6.0.3 on 2026-04-15 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'academic year',
                'verbose_name_plural': 'academic years',
                'db_table': 'students_academic_year',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('numeric_name', models.IntegerField(unique=True)),
                ('stream', models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('', 'None')], max_length=50)),
                ('capacity', models.IntegerField(default=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'class level',
                'verbose_name_plural': 'class levels',
                'db_table': 'students_class_level',
                'ordering': ['numeric_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'students_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(default=40)),
                ('room_no', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.classlevel')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'db_table': 'students_section',
                'ordering': ['name'],
                'unique_together': {('class_level', 'name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50, unique=True)),
                ('admission_date', models.DateField()),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('hinduism', 'Hinduism'), ('christianity', 'Christianity'), ('buddhism', 'Buddhism'), ('other', 'Other')], max_length=20)),
                ('aadhar_no', models.CharField(blank=True, max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('father_phone', models.CharField(blank=True, max_length=20)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('mother_phone', models.CharField(blank=True, max_length=20)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('house', models.CharField(blank=True, max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('tc_no', models.CharField(blank=True, max_length=50)),
                ('tc_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('studying', 'Studying'), ('transferred', 'Transferred'), ('passed_out', 'Passed Out'), ('left', 'Left'), ('suspended', 'Suspended')], default='studying', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.classlevel')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'students_student',
                'ordering': ['roll_number', 'admission_no'],
            },
        ),
        migrations.CreateModel(
            name='StudentPromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('from_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='students.academicyear')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_from', to='students.classlevel')),
                ('promoted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_promotions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student')),
                ('to_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='students.academicyear')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_to', to='students.classlevel')),
            ],
            options={
                'verbose_name': 'student promotion history',
                'verbose_name_plural': 'student promotion histories',
                'db_table': 'students_promotion_history',
                'ordering': ['-promoted_at'],
            },
        ),
    ]
