# Generated by Django 6.0.3 on 2026-04-17 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'academic_year', 'class_level', 'section'], name='student_status_yr_cls_sec_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['academic_year', 'is_active', 'status'], name='student_yr_active_status_idx'),
        ),
    ]
