# Generated by Django 5.2.12 on 2026-03-09 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('from_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='students.academicyear')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_from', to='students.classlevel')),
                ('promoted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_promotions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.student')),
                ('to_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='students.academicyear')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_to', to='students.classlevel')),
            ],
            options={
                'verbose_name': 'student promotion history',
                'verbose_name_plural': 'student promotion histories',
                'db_table': 'students_promotion_history',
                'ordering': ['-promoted_at'],
            },
        ),
    ]
