# Generated by Django 5.2.12 on 2026-04-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_father_name_student_father_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_email',
        ),
    ]
