# Generated by Django 6.0.3 on 2026-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('fees', '0001_initial'),
        ('students', '0002_student_student_status_yr_cls_sec_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['academic_year', 'status', 'due_date'], name='fee_invoice_yr_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['student', 'academic_year', 'due_amount'], name='fee_invoice_stu_yr_due_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_date', 'created_at'], name='fee_payment_date_created_idx'),
        ),
    ]
