# Generated by Django 6.0.3 on 2026-04-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('stats', 'Statistics'), ('chart', 'Chart'), ('table', 'Table'), ('list', 'List')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Widget configuration')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('for_roles', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'dashboard widget',
                'verbose_name_plural': 'dashboard widgets',
                'db_table': 'dashboard_widget',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'system setting',
                'verbose_name_plural': 'system settings',
                'db_table': 'dashboard_settings',
            },
        ),
    ]
