# Generated by Django 5.2.12 on 2026-04-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Convert empty strings to NULL first
                "UPDATE accounts_user SET phone = NULL WHERE phone = ''",
                # Add unique index (SQLite supports partial unique index via WHERE)
                "CREATE UNIQUE INDEX accounts_user_phone_unique ON accounts_user (phone) WHERE phone IS NOT NULL",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS accounts_user_phone_unique",
                "UPDATE accounts_user SET phone = '' WHERE phone IS NULL",
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='phone',
                    field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
                ),
            ],
        ),
    ]
