# Generated by Django 5.2.12 on 2026-03-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_no', models.IntegerField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('break_duration', models.IntegerField(default=0, help_text='Break duration in minutes')),
            ],
            options={
                'verbose_name': 'period',
                'verbose_name_plural': 'periods',
                'db_table': 'academics_period',
                'ordering': ['period_no'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('subject_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('practical', 'Practical')], default='core', max_length=20)),
                ('credit_hours', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'db_table': 'academics_subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_class_teacher', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'teacher subject assignment',
                'verbose_name_plural': 'teacher subject assignments',
                'db_table': 'academics_teacher_subject_assignment',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('room_no', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'timetable',
                'verbose_name_plural': 'timetables',
                'db_table': 'academics_timetable',
                'ordering': ['day_of_week', 'period__period_no'],
            },
        ),
    ]
