# Generated by Django 5.2.12 on 2026-04-02 06:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year_end_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12)),
                ('term_structure', models.CharField(choices=[('two', 'Two Terms (Jan-Jun, Jul-Dec)'), ('three', 'Three Terms')], default='two', max_length=20)),
                ('working_days', models.JSONField(default=list, help_text='Indices: 0=Sunday ... 6=Saturday')),
                ('school_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('school_end_time', models.TimeField(default=datetime.time(14, 0))),
                ('period_duration', models.IntegerField(default=45, help_text='Minutes')),
                ('periods_per_day', models.IntegerField(default=7)),
                ('min_class', models.IntegerField(default=1)),
                ('max_class', models.IntegerField(default=12)),
                ('section_naming', models.CharField(choices=[('alpha', 'A, B, C, D'), ('numeric', '1, 2, 3')], default='alpha', max_length=20)),
                ('max_sections_per_class', models.IntegerField(default=4)),
                ('max_students_per_section', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Academic Setting',
                'verbose_name_plural': 'Academic Settings',
                'db_table': 'settings_academic',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('late_threshold_minutes', models.IntegerField(default=10)),
                ('attendance_types', models.JSONField(default=list, help_text="['present', 'absent', 'late', 'leave']")),
            ],
            options={
                'verbose_name': 'Attendance Setting',
                'verbose_name_plural': 'Attendance Settings',
                'db_table': 'settings_attendance',
            },
        ),
        migrations.CreateModel(
            name='ExaminationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_distribution_type', models.CharField(choices=[('board', 'Board Pattern (MCQ + Written)'), ('custom', 'Custom')], default='board', max_length=20)),
                ('total_marks_per_subject', models.IntegerField(default=100)),
                ('board_exam_classes', models.JSONField(default=list, help_text='[10, 12] - Classes with board exams (SSC/HSC)')),
            ],
            options={
                'verbose_name': 'Examination Setting',
                'verbose_name_plural': 'Examination Settings',
                'db_table': 'settings_examination',
            },
        ),
        migrations.CreateModel(
            name='ExamTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, max_length=100)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.IntegerField(default=100)),
                ('pass_marks', models.IntegerField(default=33)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exam Type Config',
                'verbose_name_plural': 'Exam Type Configs',
                'db_table': 'settings_exam_type_config',
                'ordering': ['weightage'],
            },
        ),
        migrations.CreateModel(
            name='FeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='৳', max_length=5)),
                ('late_fee_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee_grace_days', models.IntegerField(default=10)),
                ('max_late_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('receipt_prefix', models.CharField(default='RCP', max_length=10)),
                ('allow_partial_payment', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fee Setting',
                'verbose_name_plural': 'Fee Settings',
                'db_table': 'settings_fee',
            },
        ),
        migrations.CreateModel(
            name='GradingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa_scale', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=33.0, max_digits=5)),
                ('include_fourth_subject', models.BooleanField(default=True)),
                ('fail_on_compulsory_subject', models.BooleanField(default=True)),
                ('grade_display_format', models.CharField(choices=[('letter', 'Letter'), ('gpa', 'GPA'), ('both', 'Both')], default='both', max_length=20)),
            ],
            options={
                'verbose_name': 'Grading Setting',
                'verbose_name_plural': 'Grading Settings',
                'db_table': 'settings_grading',
            },
        ),
        migrations.CreateModel(
            name='LibrarySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_books_per_student', models.IntegerField(default=3)),
                ('max_books_per_teacher', models.IntegerField(default=5)),
                ('issue_duration_days', models.IntegerField(default=14)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('max_fine', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('renewal_allowed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Library Setting',
                'verbose_name_plural': 'Library Settings',
                'db_table': 'settings_library',
            },
        ),
        migrations.CreateModel(
            name='PromotionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_promote', models.BooleanField(default=False)),
                ('minimum_gpa_for_promotion', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('max_failed_subjects', models.IntegerField(default=0)),
                ('allow_supplementary_exam', models.BooleanField(default=True)),
                ('supplementary_pass_percentage', models.DecimalField(decimal_places=2, default=33.0, max_digits=5)),
                ('require_attendance_for_promotion', models.BooleanField(default=True)),
                ('promotion_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
            ],
            options={
                'verbose_name': 'Promotion Setting',
                'verbose_name_plural': 'Promotion Settings',
                'db_table': 'settings_promotion',
            },
        ),
        migrations.CreateModel(
            name='ReportCardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_attendance', models.BooleanField(default=True)),
                ('show_teacher_remarks', models.BooleanField(default=True)),
                ('show_class_rank', models.BooleanField(default=False)),
                ('show_gpa', models.BooleanField(default=True)),
                ('show_fourth_subject_bonus', models.BooleanField(default=True)),
                ('show_school_logo', models.BooleanField(default=True)),
                ('show_board_name', models.BooleanField(default=True)),
                ('signature_fields', models.JSONField(default=list, help_text="['head_teacher', 'class_teacher', 'parent']")),
            ],
            options={
                'verbose_name': 'Report Card Setting',
                'verbose_name_plural': 'Report Card Settings',
                'db_table': 'settings_report_card',
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_bn', models.CharField(max_length=200, verbose_name='Name (Bangla)')),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('eiin', models.CharField(blank=True, max_length=20, verbose_name='EIIN')),
                ('board_name', models.CharField(choices=[('dhaka', 'Dhaka'), ('rajshahi', 'Rajshahi'), ('chittagong', 'Chittagong'), ('comilla', 'Comilla'), ('jessore', 'Jessore'), ('dinajpur', 'Dinajpur'), ('sylhet', 'Sylhet'), ('barisal', 'Barisal'), ('mymensingh', 'Mymensingh'), ('madrasa', 'Madrasa'), ('technical', 'Technical')], default='dhaka', max_length=50)),
                ('medium', models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('both', 'Both')], default='bangla', max_length=20)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('day', 'Day'), ('evening', 'Evening')], default='day', max_length=20)),
                ('school_type', models.CharField(choices=[('government', 'Government'), ('non_government', 'Non-Government'), ('private', 'Private'), ('semi_government', 'Semi-Government')], default='non_government', max_length=30)),
                ('gender_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('co_educational', 'Co-Educational')], default='co_educational', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('madrasa', 'Madrasa'), ('technical', 'Technical')], default='general', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='settings/')),
                ('established_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
                'db_table': 'settings_school_info',
            },
        ),
        migrations.CreateModel(
            name='StudentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no_prefix', models.CharField(default='ADM', max_length=10)),
                ('admission_no_format', models.CharField(default='{prefix}-{year}-{seq}', max_length=50)),
                ('admission_no_sequence_length', models.IntegerField(default=4)),
                ('photo_required', models.BooleanField(default=True)),
                ('blood_group_required', models.BooleanField(default=False)),
                ('religion_required', models.BooleanField(default=True)),
                ('birth_certificate_required', models.BooleanField(default=True)),
                ('track_previous_school', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Student Setting',
                'verbose_name_plural': 'Student Settings',
                'db_table': 'settings_student',
            },
        ),
        migrations.CreateModel(
            name='TransportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_calculation_type', models.CharField(choices=[('distance', 'Distance'), ('route', 'Route'), ('flat', 'Flat')], default='route', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Transport Setting',
                'verbose_name_plural': 'Transport Settings',
                'db_table': 'settings_transport',
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(max_length=5)),
                ('min_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('grading_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='settings_app.gradingsetting')),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'db_table': 'settings_grade_scale',
                'ordering': ['-min_marks'],
            },
        ),
    ]
