# Generated by Django 6.0.3 on 2026-04-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_order', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'route stop',
                'verbose_name_plural': 'route stops',
                'db_table': 'transport_route_stop',
                'ordering': ['stop_order'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'transport route',
                'verbose_name_plural': 'transport routes',
                'db_table': 'transport_route',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Car'), ('other', 'Other')], max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=20)),
                ('driver_license', models.CharField(blank=True, max_length=50)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('permit_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='transport/vehicles/')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'db_table': 'transport_vehicle',
            },
        ),
        migrations.CreateModel(
            name='TransportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fees', to='students.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fees', to='students.student')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='transport.transportroute')),
            ],
            options={
                'verbose_name': 'transport fee',
                'verbose_name_plural': 'transport fees',
                'db_table': 'transport_fee',
            },
        ),
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='students.academicyear')),
                ('drop_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_students', to='transport.routestop')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_students', to='transport.routestop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='students.student')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transport.transportroute')),
            ],
            options={
                'verbose_name': 'transport assignment',
                'verbose_name_plural': 'transport assignments',
                'db_table': 'transport_assignment',
            },
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.transportroute'),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transport.vehicle'),
        ),
    ]
