# Generated by Django 5.2.12 on 2026-03-09 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0002_studentpromotionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='students.academicyear'),
            preserve_default=False,
        ),
    ]
