# Generated by Django 6.0.3 on 2026-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0002_initial'),
        ('attendance', '0001_initial'),
        ('students', '0002_student_student_status_yr_cls_sec_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['academic_year', 'date', 'status'], name='attendance_yr_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'academic_year', 'date'], name='attendance_stu_yr_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['academic_year', 'status', 'created_at'], name='leave_year_status_created_idx'),
        ),
    ]
