# Generated by Django 5.2.12 on 2026-03-09 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('attendance', '0002_leaverequest_academic_year'),
        ('students', '0002_studentpromotionhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_permissions', to='students.academicyear')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_attendance_permissions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permissions', to='students.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permissions', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'teacher attendance permission',
                'verbose_name_plural': 'teacher attendance permissions',
                'db_table': 'attendance_teacher_permission',
                'unique_together': {('teacher', 'section', 'academic_year')},
            },
        ),
    ]
