# Generated by Django 6.0.3 on 2026-04-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weightage', models.DecimalField(decimal_places=2, help_text='Weightage in percentage', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'exam type',
                'verbose_name_plural': 'exam types',
                'db_table': 'examinations_exam_type',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_letter', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'Fail')], max_length=2)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'db_table': 'examinations_grade',
                'ordering': ['student', 'subject', 'exam_type'],
            },
        ),
        migrations.CreateModel(
            name='GradeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_letter', models.CharField(max_length=2)),
                ('grade_points', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
            options={
                'verbose_name': 'grade distribution',
                'verbose_name_plural': 'grade distributions',
                'db_table': 'examinations_grade_distribution',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'term',
                'verbose_name_plural': 'terms',
                'db_table': 'examinations_term',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('marks', models.IntegerField()),
                ('room_no', models.CharField(blank=True, max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this exam schedule is published and visible to students')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='students.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='students.classlevel')),
            ],
            options={
                'verbose_name': 'exam schedule',
                'verbose_name_plural': 'exam schedules',
                'db_table': 'examinations_schedule',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
