# Generated by Django 5.2.12 on 2026-03-09 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('examinations', '0001_initial'),
        ('students', '0002_studentpromotionhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='students.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('exam_type', 'subject', 'class_level', 'academic_year')},
        ),
    ]
