# Generated by Django 6.0.3 on 2026-04-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0002_initial'),
        ('examinations', '0001_initial'),
        ('questions', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='question_paper',
            field=models.ForeignKey(blank=True, help_text='Question paper to be used for this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='questions.questionpaper'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examinations.examtype'),
        ),
        migrations.AddField(
            model_name='grade',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='grade',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_grades', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='grade',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='examinations.examtype'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='gradedistribution',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_distributions', to='students.classlevel'),
        ),
        migrations.AddField(
            model_name='gradedistribution',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_distributions', to='examinations.examtype'),
        ),
        migrations.AddField(
            model_name='gradedistribution',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_distributions', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='examinations.term'),
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('name', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('exam_type', 'subject', 'class_level', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='gradedistribution',
            unique_together={('class_level', 'subject', 'exam_type', 'grade_letter')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('name', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'exam_type', 'academic_year')},
        ),
    ]
