# Generated by Django 6.0.3 on 2026-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('examinations', '0002_initial'),
        ('questions', '0001_initial'),
        ('students', '0002_student_student_status_yr_cls_sec_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['academic_year', 'class_level', 'date'], name='exam_sched_yr_class_date_idx'),
        ),
    ]
