# Generated by Django 5.2.12 on 2026-04-09 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_alter_examschedule_unique_together_and_more'),
        ('questions', '0002_questionpaper_questionpaperquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this exam schedule is published and visible to students'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='question_paper',
            field=models.ForeignKey(blank=True, help_text='Question paper to be used for this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='questions.questionpaper'),
        ),
    ]
